### ISSUE TITLE
Featuretest for fdk-dataset-harvester-gui

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-dataset-harvester-gui#6]
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
fdk-dataset-harvester-gui

**Comment by stigbd** [comment]
Lukker denne sidan tjenesten no er realisert av https://github.com/Informasjonsforvaltning/fdk-admin-gui
